# Generated by Django 4.1.7 on 2023-03-07 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorten',
            name='createdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shorten',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
